### ISSUE TITLE
How to get activity logs in talkyard-prod

### ISSUE THREAD

**Issue by ajaymohanbisht** [debiki/talkyard-prod-one#2]
Hello,
I have installed talkyard-prod on one of my aws server. I need to get human readable logs for user activity. Is there any way I can get it with some configuration changes.

**Comment by kajmagnus** [comment]
Hi @ajaymohanbisht, what kind of user activity do you have in mind?

Is it for auditing? Information about things users do (e.g. about a moderator deleting or approving a comment, or a user flagging something, or deleting his/her comment), get saved to an audit log. I haven't yet built an interface, for viewing this audit log. I'm going to need to view the audit log me too, so maybe I should start building this view-logs interface, next week.

Then there's the log of things people have said and posted, if that's what you had in mind? For example:
https://usability.testing.exchange/-/users/kajmagnus/activity/posts

**Comment by ajaymohanbisht** [comment]
Hi Kajmagnus,
Thanks for your reply
Yes I am looking for something like audit log but in JSON or some format that can be read programmatically. For now, We are not looking for an interface. Please let me know where can I find audit log in talkyard-prod files.

**Comment by kajmagnus** [comment]
@ajaymohanbisht Okay, I can make the audit log data available in both JSON and in a human friendly interface.

The JSON format will maybe be a bit unstable — maybe some months later, I will feel I need to change something. And maybe then something will break, if you've assumed a certain JSON format.  I could notify you about that in advance .... And then it'd be good to know how you're looking to use this JSON data? So I better understand, if a change I make, is backwards compatible with your system(s) or not.

Are you for example looking to ... watch for certain types of events, and then create internal "alarms" to other systems you have? Maybe not PagerDuty but sth similar? or maybe a notification to a Slack chat channel?

What kind of events? E.g. comments posted, or topics created? Or something-got-flagged? Or a-new-user-joined-the-site?

**Comment by ajaymohanbisht** [comment]
@kajmagnus 
I am trying to create a service that tracks activities of a user on Talkyard, for which I have to monitor every event performed by a user.
For example, Service will monitor when a user joins, new question created or upvoted or any other activity.

Regardless of the log format type (.json or .txt or .log) if Talkyard store such logs already (maybe in audit log as you have mentioned) please let me know the location to find this log on Ubuntu 16.04 Server.

Also, If there is some workaround via some code changes to generate this log you can let me know.

**Comment by ajaymohanbisht** [comment]
@kajmagnus 
Thanks for this important information.Yes, Please post this discussion to Talkyard Forum. 

I have one more question, Now  As I have accessed tables in talkyard database. Can you let me where is mapping for ```did_what``` column in the ```audit_log3``` table? 

How can I know which number means what ?. Can you let me know where mapping of these values is stored ?

**Comment by kajmagnus** [comment]
@ajaymohanbisht  Okay, and here are the audit log entry types for the `did_what` column:

https://github.com/debiki/talkyard/blob/e9bcf021223831b8522553f6fbaab418323ab615/modules/ed-core/src/main/scala/com/debiki/core/AuditLogEntry.scala#L32

Some types of events are missing — I'll start audit logging more different types of things, later on / soon.

And this is going to be a little bit fragile — maybe in the future I'll change the audit log table, e.g. add or rename columns. I can add a note about notifying you, then.

Also, later on, I can make available a HTTP JSON endpoint, which will be simpler to keep backwards compatible.  (For example, maybe there could even be a version number HTTP URL param, like `?apiVersion=123`.) Then you can change from accessing the database, to reading data from that JSON endpoint instead, how about that?

And it'd be accessible only on localhost, or there'd be some auth method.

And / or maybe webhooks could be useful for you too. Then your app could just listen, and get notified via a HTTP POST whenever sth happens

**Comment by ajaymohanbisht** [comment]
Hello Kaj @kajmagnus ,

Thanks for your much-needed help. You can close this issue.

**Comment by kajmagnus** [comment]
Hi again, ok, closed now.  Hmm, you and `Arjun @exam4india5` here:

https://www.talkyard.io/-87/how-can-i-connect-external-postgresql-database-to-talkyard-prod

posted about fairly much the same things, at the same time — are you connected somehow, e.g. the same company / organization? if I may ask
